### ISSUE TITLE
Uncaught TypeError: Cannot read property 'role' of undefined

### ISSUE THREAD

**Issue by l-l-l-l-l-l-l-l-l** [Sentero-esp12/Multi-Premoves-Mouse-Keyboard#17]
<img width="646" alt="a error" src="https://user-images.githubusercontent.com/63735991/95534309-13bad100-09ab-11eb-8925-3e7a7077974c.png">

Context link: https://lichess.org/tE6ZkdrzTfaZ

**Comment by Sentero-esp12** [comment]
It's probably fixed, bump this thread in case it appears again
