### ISSUE TITLE
Cant play when extension is enabled

### ISSUE THREAD

**Issue by slawosz** [Sentero-esp12/Multi-Premoves-Mouse-Keyboard#19]
https://lichess.org/forum/lichess-feedback/bug-118

**Comment by BreakTos** [comment]
After contacting a kind moderator of lichess , I got to know that there was a update in lichess today .

I don't know but if there are some changes required to be done by developer after every update , I request them to look into this

![122](https://user-images.githubusercontent.com/76687690/103214540-b04f9800-4936-11eb-800c-5d31617296f1.PNG)

**Comment by Sentero-esp12** [comment]
Yeah, it breaks occasionally after Lichess updates. Currently it should be fixed
