### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by amoghmulge** [Sentero-esp12/Multi-Premoves-Mouse-Keyboard#20]
the pieces are selected ,but the movements don't happen when hovered over.Please help. 
I think an update is required.

**Comment by Sentero-esp12** [comment]
Did it work before? Is someone else experiencing this as well?

**Comment by amoghmulge** [comment]
No ,was using it for the first time .Maybe I need to change any settings somewhere or may be I am not using it correctly. When I hover nothing happens. Could you please give all the things we need to do or change to use it ?

**Comment by Sentero-esp12** [comment]
Basically all the information you need is in the readme. Maybe you could ask someone who is using it successfully to make a Skype call and configure it for you?
