### ISSUE TITLE
Issue with manifest

### ISSUE THREAD

**Issue by thecodingterm** [Sentero-esp12/Multi-Premoves-Mouse-Keyboard#22]
![image](https://user-images.githubusercontent.com/74772444/107215867-d2dbd300-6a03-11eb-8fff-0d340e9fa591.png)

Manifest issue 

When I play now it takes 3 seconds before the extension stops debugging browser, so I am left to play with mouse

I am TheChessPlayer21 on lichess

**Comment by Sentero-esp12** [comment]
Chrome doesn't like unknown values in the manifest, but it doesn't affect the extension. This entry is necessary for updates (I didn't want to put it in a separate file)
