### ISSUE TITLE
Problem with manifest

### ISSUE THREAD

**Issue by advayjerath** [Sentero-esp12/Multi-Premoves-Mouse-Keyboard#25]

**Comment by Ace139** [comment]
Also facing the same issue.

**Comment by Sentero-esp12** [comment]
What problem?

**Comment by advayjerath** [comment]
"update": {
        "versions": {
            "content": {
                "v": 2,
                "url": "https://raw.githubusercontent.com/Sentero-esp12/Multi-Premoves-Mouse-Keyboard/master/Extension/content.js"
            },
            "script": {
                "v": 2,
                "url": "https://raw.githubusercontent.com/Sentero-esp12/Multi-Premoves-Mouse-Keyboard/master/Extension/script.js"
            },
            "background": {
                "v": 2,
                "url": "https://raw.githubusercontent.com/Sentero-esp12/Multi-Premoves-Mouse-Keyboard/master/Extension/background.js"
            }
        },
        "additionalSettings": {}
    },
this is the error

**Comment by advayjerath** [comment]
Unrecognized manifest key 'update'.

**Comment by advayjerath** [comment]
hi can i message you on lichess

**Comment by Sentero-esp12** [comment]
This is just a warning, it doesn't affect the performance of the extension

**Comment by advayjerath** [comment]
my kb is not coming

**Comment by advayjerath** [comment]
only multipremoves

**Comment by Sentero-esp12** [comment]
You should enable it in the settings (the extension icon)

**Comment by advayjerath** [comment]
is it a problem with  with my kb because it works fine but only multipremoves is can be used

**Comment by advayjerath** [comment]
hi can i talk to you in personal

**Comment by advayjerath** [comment]
> You should enable it in the settings (the extension icon)

already done

**Comment by Sentero-esp12** [comment]
Yeah, write me on Lichess

**Comment by advayjerath** [comment]
your account name

**Comment by Sentero-esp12** [comment]
BerserkAsIfUWereMad

**Comment by advayjerath** [comment]
you dont accept new messages

**Comment by advayjerath** [comment]
disable it from your lichess settings

**Comment by Sentero-esp12** [comment]
Done

**Comment by advayjerath** [comment]
hi

**Comment by advayjerath** [comment]
again it is not working
