### ISSUE TITLE
extension is not working

### ISSUE THREAD

**Issue by advayjerath** [Sentero-esp12/Multi-Premoves-Mouse-Keyboard#27]

**Comment by Sentero-esp12** [comment]
Some Lichess code changed

**Comment by kildsolus** [comment]
I tried deleting some of the errored code to see if it would allow me to interact with the page, and it did. The issue is after you delete it, you can no longer drag and drop your pieces onto the board.


          let stateMatch = completed.match(
            /const ([a-zA-Z]+) ?= ?([a-zA-Z0-9_]+)\.defaults\(\);/
          )[0];
          let localConst = stateMatch
            .match(/const ([a-zA-Z]+) ?=/)[0]
            .substr(6)
            .replace(/ ?=/, '');
          completed = completed.replace(
            stateMatch,
            `const ${localConst} = globalStateReference = ${
              stateMatch.match(/([a-zA-Z]+)\.defaults\(\);/)[0]
            }`
          );

          let boardMatch = completed.match(
            /[a-zA-Z]+=[a-zA-Z]+\(\(function\([a-zA-Z]+,[a-zA-Z]+\){function [a-zA-Z]+\([a-zA-Z]+,\.\.\.[a-zA-Z]+\)/
          )[0];
          let replaceWith = boardMatch.replace('=', '=globalBoardReference=');
          completed = completed.replace(boardMatch, replaceWith);


I suppose that this code does that.

**Comment by Sentero-esp12** [comment]
Yes, this code extracts certain variables and objects from Lichess code to then use them to make moves. The problem is apparently that `.match(
        /const ([a-zA-Z]+) ?= ?([a-zA-Z0-9_]+)\.defaults\(\);/
      )[0]` doesn't return anything, so it has to be changed. I guess one needs to check Lichess compliled code before the changes took place and try to find it again in the new code. This might be complicated

**Comment by Sentero-esp12** [comment]
Here's `round.js` from long ago, where the parts the regex is searching for still existed: https://github.com/Sentero-esp12/Multi-Premoves-Mouse-Keyboard/blob/master/round.js
So the regex is searching for something with `.defaults` in it. The same changed line should be found in the new round.js and regex should be adjusted to match it correctly

**Comment by advayjerath** [comment]
hmm so is the extension fixed

**Comment by advayjerath** [comment]
ya we  have to do it fast so i will contribute

**Comment by StasisD** [comment]
> I guess one needs to check Lichess compiled code before the changes took place (`round.js`) and try to find it again in the new code. This might be complicated. I should have commented the necessary line nearby, but I didn't think the code would change

I actually have the lila master downloaded from 4-20-2021, Idk if that would help repair the extension.

Also I found this nonsense https://github.com/ornicar/lila/blob/70e809156c30ced0dbccbf0fea8bdb11bcac7f27/public/javascripts/vendor/chessground.min.js 

Idk if its relevant though

**Comment by goodkarma07** [comment]
> Here's `round.js` from long ago, where the parts the regex is searching for still existed: https://github.com/Sentero-esp12/Multi-Premoves-Mouse-Keyboard/blob/master/round.js
> So the regex is searching for something with `.defaults` in it. The same changed line has to be found in the new `round.js` (Developer Tools -- Sources -- Page -- lichess1.org -- assets -- compiled -- round.js) and regex has to be adjusted to match it correctly

Can you dm me my username is zerkback all on lichess, I would like to get a better understanding of the problem as my dad is a coder and understands javascript.

**Comment by Sentero-esp12** [comment]
Here's a list of things that might help:
1. What the broken part of the `content.js` does is it's intercepting their (round.js) code and instead of
`const a = x.StateObject` it replaces it with `const a = someVariableThatIsAccessibleFromTheExtension = x.StateObject`, by using regexes. It does it to get access to Lichess state at any time, such as pieces position, current color, legal moves and so on. 
2. I've uploaded the old `round.js` to the repository, where those regexes still found relevant strings.
3. One of the regexes is looking for something with `.default` in its name, which doesn't exist in the new `round.js`. What it's looking for is this line (962) in the old code:
```
        t.defaults = function() {
            return {
                pieces: h.read(h.initial),
```
4. In the new code it's the line 2417:
```
const o = {
pieces: Xt(Ut),
```
5. It might be the only problem, or other regexes might be broken too.
6. It might help to use mskchess.ru, because they have unminified `round.js` (Developer Tools -- Sources -- Page), so one could get a good understanding of what their code is doing. They are still using the old round.js however. 
7. It might help to use VSCode or another editor's `go to definition` feature to find the place where a string of the code has to be replaced.

**Comment by advayjerath** [comment]
hmm ok

**Comment by advayjerath** [comment]
Is extension fixed
Ifno Pls fix

**Comment by advayjerath** [comment]
Whn will it vetfixed

**Comment by advayjerath** [comment]
Get fi esd

**Comment by advayjerath** [comment]
Get it fixed

**Comment by Vanish14** [comment]
![image](https://user-images.githubusercontent.com/38332370/122239152-639e5000-cec9-11eb-9c86-05f2e04c1aeb.png)

Lichess doesn't working with extension :(

**Comment by goodkarma07** [comment]
I fixed it.

**Comment by Ole-rgb** [comment]
> 
> I fixed it.

How did you fix itgoodkarma07, because I know very little about java but would still like to use the extension?

**Comment by goodkarma07** [comment]
Ah, I just found a old october  version of the keyboard with the correct
round.js!

**Comment by Mahatma00Gandhi** [comment]
@goodkarma07 oh please link it here for us too

**Comment by goodkarma07** [comment]
Using an old october version of kb

**Comment by Mahatma00Gandhi** [comment]
@goodkarma07 so instead of directly using this premove add-on you are using KB extension which includes premoves ?

**Comment by Sentero-esp12** [comment]
[Multi-Premoves-Mouse-Keyboard-master.zip](https://github.com/Sentero-esp12/Multi-Premoves-Mouse-Keyboard/files/6682713/Multi-Premoves-Mouse-Keyboard-master.zip)

This is the version he is using. It has a big banner warning at the top though

**Comment by Mahatma00Gandhi** [comment]
@Sentero-esp12 so i will install this too thanks for the help :)

**Comment by goodkarma07** [comment]
Thanks sorry I did not know how to explain that

**Comment by Mahatma00Gandhi** [comment]
@Sentero-esp12 @goodkarma07 the extension you liked works fine on my computer i am new to it so it's a bit hard for now but it's nice

So can i use this extension on mobile using yandex alpha(it's a browser which supports extensions) without any problems ?

**Comment by Sentero-esp12** [comment]
@Mahatma00Gandhi last time I checked (maybe in autumn) it didn't work in the Yandex browser

**Comment by Mahatma00Gandhi** [comment]
@Sentero-esp12 well i had tried the latest version of this extension and it said while installing that "round.js is corrupt" or something like that so i guess it doesn't work


Also why did you stop the work on this project this is really nice

**Comment by goodkarma07** [comment]
Just switch the extensions from old to new.

**Comment by goodkarma07** [comment]
Or I mean new to old.

**Comment by Sentero-esp12** [comment]
@Mahatma00Gandhi My interests have changed and I'm not playing ultra competitively anymore or using keyboard. Perhaps I should set up a fundraiser, to work for a certain amount per hour if people donate. Or someone else could take on this project instead.

**Comment by Mahatma00Gandhi** [comment]
@goodkarma07 well i will try as it works for Computer

**Comment by Mahatma00Gandhi** [comment]
@Sentero-esp12 i understand 

So what was your peak ultrabullet rating ?

**Comment by goodkarma07** [comment]
Like 2500 ;)

**Comment by Mahatma00Gandhi** [comment]
@goodkarma07 bruh as of right now that would place you in top 5 on lichess this is insane

**Comment by goodkarma07** [comment]
Yes :) top 10 right now

**Comment by Mahatma00Gandhi** [comment]
@goodkarma07 i believe you are p4ssion. Am i right ?

**Comment by goodkarma07** [comment]
No lol I am zerkbackall

**Comment by Mahatma00Gandhi** [comment]
@goodkarma07 oof my bad lol as of right now u 11th but i guess you'll be back in top 10 

What do you think about the ethics of keyboard and more importantly multi premove ?

**Comment by goodkarma07** [comment]
Eh I lost points because I stopped multipremove the accuracy on the
keyboard input has a much better accuracy.

**Comment by Mahatma00Gandhi** [comment]
Oh why did you stop multi premove ?

**Comment by goodkarma07** [comment]
The accuracy is weak.

**Comment by Mahatma00Gandhi** [comment]
@goodkarma07 so do you think multi premove and keyboard is right to use and isn't cheating ?

**Comment by goodkarma07** [comment]
It's not cheating

**Comment by Mahatma00Gandhi** [comment]
@goodkarma07 yeah i too believe so but what's the justification that it isn't ? Why do you believe so ?

**Comment by needmultitoflagmorelag** [comment]
well there's no single version of multis that works for me. i checked the version posted above by sentero, saying zerk uses it, but it's not working either. the difference that i found is this one pops extension started debugging your browser text on top when opening lichess, but when i start actual game it still doesn't load the gamee basically like any other versions i've seen. how can i make it work? apparently it does work for zerk, do i need any specific version of chrome or something? hope i get response, thanks.

**Comment by Mahatma00Gandhi** [comment]
@needmultitoflagmorelag well i have used that one

And yes it has the debugging problem but it's bearable

The real problem starts when it doesn't make multi premoves half of the time for some reason

Won't blame anyone because afterall the development has stopped

**Comment by Sentero-esp12** [comment]
Should be fixed

**Comment by needmultitoflagmorelag** [comment]
so is it fixed now?

**Comment by Sentero-esp12** [comment]
Yes, the current version is working as of now
